// Generated by CoffeeScript 1.6.3
(function() {
  var autoBackground;

  autoBackground = function(element) {
    var c, ctx, img, pixel;
    c = document.getElementById(element);
    ctx = c.getContext("2d");
    img = document.getElementById("preview");
    ctx.drawImage(img, 10, 10);
    return pixel = context.getImageData(x, y, 1, 1).data;
  };

}).call(this);
